name: authc1_flutter
description: Flutter integration for AuthC1.
version: 0.0.1-dev.8
homepage: 'https://authc1.com'

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  path_provider: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

platforms:
  android:
  ios:
  macos:
  web:
  windows:

flutter:
