export enum EventsConfig {
  UserRegistered = "user.registered",
  UserLoggedIn = "user.loggedIn",
  UserLoggedOut = "user.loggedOut",
  UserTokenRefreshed = "user.tokenRefreshed",
  UserPasswordReset = "user.passwordReset",
  UserEmailVerified = "user.emailVerified",
  UserPhoneVerified = "user.phoneVerified",
  UserOtpSent = "user.otpSent",
  UserOtpVerified = "user.otpVerified",
  UserAccountLocked = "user.accountLocked",
  UserAccountUnlocked = "user.accountUnlocked",
  UserPasswordChanged = "user.passwordChanged",
  UserProfileUpdated = "user.profileUpdated",
  UserLoginError = "user.loginError",
  UserOtpSendError = "user.otpSendError",
  UserOtpConfirmError = "user.otpConfirmError",
  UserPasswordResetError = "user.passwordResetError",
  UserEmailVerificationError = "user.emailVerificationError",
  UserEmailVerificationSent = "user.emailVerificationSent",
  UserPhoneVerificationSent = "user.phoneVerificationSent",
}
